[build]
builder = "NIXPACKS"
buildCommand = "pip install fastapi uvicorn"

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"

[env]
PYTHON_VERSION = "3.11.0"
